name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger when a new GitHub release is published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Build package
      run: |
        uv build
      env:
        # Restrict which subprojects are included in the build
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.release.tag_name }}

    - name: Publish to PyPI
      run: |
        uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}